Let stunnerctl fail gracefully when no configmap is found

diff --git a/cmd/stunnerctl/stunnerctl b/cmd/stunnerctl/stunnerctl
--- a/cmd/stunnerctl/stunnerctl
+++ b/cmd/stunnerctl/stunnerctl
@@ -19,9 +19,12 @@ running_config () {
     name=${args[1]}
     [ -z $namespace -o -z $name ] && echo "cannot parse <namespace/name> argument" && exit 0
 
+    [ $(kubectl get cm -n $namespace -o json| jq ".items | map(select(.metadata.name==\"${name}\"))|length") -eq 0 ] && \
+        echo "STUNner configmap ${namespace}/${name} not found" && exit 1
+
     tmpfile=$(mktemp "./stunnerd-config.XXXXXX")
     kubectl get cm -n $namespace $name -o jsonpath="{.data.stunnerd\.conf}" > $tmpfile
-   
+
     local AUTH_TYPE=$($jq ".auth.type" $tmpfile)
     local USERNAME=$($jq ".auth.credentials.username" $tmpfile)
     local PASSWORD=$($jq ".auth.credentials.password" $tmpfile)
@@ -31,23 +34,29 @@ running_config () {
     [ -n "$USERNAME" -a "$USERNAME" != "null" ]   && echo -e "STUN/TURN username:\t\t$USERNAME"
     [ -n "$PASSWORD" -a "$PASSWORD" != "null" ]   && echo -e "STUN/TURN password:\t\t$PASSWORD"
     [ -n "$SECRET" -a "$SECRET" != "null" ]       && echo -e "STUN/TURN secret:\t\t$SECRET"
-    
-    local n=0
-    for NAME in $($jq '.listeners[] | .name' $tmpfile); do
-        local PROTOCOL=$($jq ".listeners[${n}].protocol" $tmpfile)
-        local PUBLIC_ADDR=$($jq ".listeners[${n}].public_address" $tmpfile)
-        local PUBLIC_PORT=$($jq ".listeners[${n}].public_port" $tmpfile)
 
-        n=$((n+1))
+    if [ $($jq '.listeners | length' $tmpfile) -gt 0 ]; then {
+        local n=0
 
-        echo -e "Listener ${n}"
-        [ -n "$NAME" -a "$NAME" != "null" ]               && echo -e "\tName:\t$NAME"
-        [ -n "$NAME" -a "$NAME" != "null" ]               && echo -e "\tListener:\t$NAME"
-        [ -n "$PROTOCOL" -a "$PROTOCOL" != "null" ]       && echo -e "\tProtocol:\t$PROTOCOL"
-        [ -n "$PUBLIC_ADDR" -a "$PUBLIC_ADDR" != "null" ] && echo -e "\tPublic address:\t$PUBLIC_ADDR"
-        [ -n "$PUBLIC_PORT" -a "$PUBLIC_PORT" != "null" ] && echo -e "\tPublic port:\t$PUBLIC_PORT"
-    done
-        
+        for NAME in $($jq '.listeners[] | .name' $tmpfile); do
+            local PROTOCOL=$($jq ".listeners[${n}].protocol" $tmpfile)
+            local PUBLIC_ADDR=$($jq ".listeners[${n}].public_address" $tmpfile)
+            local PUBLIC_PORT=$($jq ".listeners[${n}].public_port" $tmpfile)
+
+            n=$((n+1))
+
+            echo -e "Listener ${n}"
+            [ -n "$NAME" -a "$NAME" != "null" ]               && echo -e "\tName:\t$NAME"
+            [ -n "$NAME" -a "$NAME" != "null" ]               && echo -e "\tListener:\t$NAME"
+            [ -n "$PROTOCOL" -a "$PROTOCOL" != "null" ]       && echo -e "\tProtocol:\t$PROTOCOL"
+            [ -n "$PUBLIC_ADDR" -a "$PUBLIC_ADDR" != "null" ] && echo -e "\tPublic address:\t$PUBLIC_ADDR"
+            [ -n "$PUBLIC_PORT" -a "$PUBLIC_PORT" != "null" ] && echo -e "\tPublic port:\t$PUBLIC_PORT"
+        done
+    } else {
+        echo No listeners
+    }
+    fi
+
     rm -f $tmpfile
 }
 
